# Build Pipeline for suil examples
image: suilteam/suil-dev:latest

# stub definition
.job_def:
  before_script: &docker_hub_login
    - docker login -u $SUILTEAM_DOCKERHUB_USER -p $SUILTEAM_DOCKERHUB_PASSWD

# build examples job
build:
  stage: build
  tags:
    - alpine
  only:
    - master

  before_script: *docker_hub_login

  script:
    - mkdir -p ./build$CI_COMMIT_TAG
    - cd ./build$CI_COMMIT_TAG
    - cmake ..
       -DCMAKE_BUILD_TYPE=Release
       -DCMAKE_INSTALL_PREFIX=`pwd`/artifacts
    - make clean install
    - cp -r ../Dockerfile ./Dockerfile
    - docker build --pull -t suilteam/suil-examples:latest .
    - docker push suilteam/suil-examples:latest
    - cd ..
